#!/bin/sh

# Clearing and caching Laravel config...
php artisan config:clear && php artisan config:cache

# Clearing and caching routes...
php artisan route:clear && php artisan route:cache

# Clearing and caching views...
php artisan view:clear && php artisan view:cache

# Linking storage...
php artisan storage:link || true

# Fixing storage permissions...
chown -R www-data:www-data /var/www/html/storage

# Starting Apache...
exec apache2-foreground